# Generated by Django 2.2.14 on 2020-07-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmodel',
            name='a_new_field',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
